"""E1 master results table (groundwork §7 — E1's main output).

Reads results/e1_baselines.csv (tuned) and results/e1_baselines_default.csv
(library defaults), validates the protocol invariants (25 rows and exactly one
config hash per (dataset, model); classical regime only), aggregates
mean ± std over the 25 shared (seed, fold) evaluations, and writes:

  analysis/output/e1_summary_long.csv              all metrics, both variants
  analysis/output/e1_master_<variant>_<metric>.csv wide dataset × model table
  analysis/output/e1_master_<variant>_<metric>.tex LaTeX (booktabs) for Ch. 7
  analysis/output/e1_delta_<metric>.csv/.tex       tuned mean − default mean

No hand-typed numbers: the thesis table is regenerated by re-running this.

Usage: python analysis/e1_summary.py [--metric balanced_accuracy | all]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import pandas as pd

RESULTS_DIR = ROOT / "results"
OUTPUT_DIR = ROOT / "analysis" / "output"
METRICS = ["accuracy", "balanced_accuracy", "f1", "roc_auc"]
EXPECTED_ROWS = 25  # 5 seeds x 5 folds, the shared splits


def load_and_validate(csv_path: Path) -> pd.DataFrame:
    df = pd.read_csv(csv_path)
    problems: list[str] = []
    if not (df["regime"] == "classical").all():
        problems.append("non-classical regime rows present (never mix regimes, §8)")
    for (dataset, model), grp in df.groupby(["dataset", "model"]):
        if len(grp) != EXPECTED_ROWS:
            problems.append(f"{dataset}/{model}: {len(grp)} rows, expected {EXPECTED_ROWS}")
        if grp["config_hash"].nunique() != 1:
            problems.append(f"{dataset}/{model}: {grp['config_hash'].nunique()} config hashes")
        if grp["split_id"].nunique() != len(grp):
            problems.append(f"{dataset}/{model}: duplicate split_ids")
    if problems:
        raise SystemExit(f"{csv_path.name} failed validation:\n  " + "\n  ".join(problems))
    return df


def long_summary(frames: dict[str, pd.DataFrame]) -> pd.DataFrame:
    parts = []
    for variant, df in frames.items():
        agg = df.groupby(["dataset", "model"])[METRICS].agg(["mean", "std"])
        agg.columns = [f"{metric}_{stat}" for metric, stat in agg.columns]
        agg = agg.reset_index()
        agg.insert(2, "variant", variant)
        parts.append(agg)
    return pd.concat(parts, ignore_index=True).round(6)


def wide_table(df: pd.DataFrame, metric: str) -> pd.DataFrame:
    grp = df.groupby(["dataset", "model"])[metric].agg(["mean", "std"])
    cells = grp.apply(lambda r: f"{r['mean']:.3f} ± {r['std']:.3f}", axis=1)
    return cells.unstack("model")


def delta_table(tuned: pd.DataFrame, default: pd.DataFrame, metric: str) -> pd.DataFrame:
    tuned_mean = tuned.groupby(["dataset", "model"])[metric].mean().unstack("model")
    default_mean = default.groupby(["dataset", "model"])[metric].mean().unstack("model")
    return (tuned_mean - default_mean).round(3)


def to_latex(df: pd.DataFrame, caption: str, label: str) -> str:
    def escape(value) -> str:
        return str(value).replace("_", r"\_")

    header_cells = " & ".join(escape(c) for c in df.columns)
    lines = [
        r"\begin{table}[ht]",
        r"\centering",
        r"\caption{" + caption + "}",
        r"\label{" + label + "}",
        r"\begin{tabular}{l" + "r" * len(df.columns) + "}",
        r"\toprule",
        "dataset & " + header_cells + r" \\",
        r"\midrule",
    ]
    for idx, row in df.iterrows():
        row_cells = " & ".join(str(v) for v in row)
        lines.append(escape(idx) + " & " + row_cells + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--metric", default="balanced_accuracy",
                        choices=METRICS + ["all"])
    args = parser.parse_args(argv)
    metrics = METRICS if args.metric == "all" else [args.metric]

    frames = {
        "tuned": load_and_validate(RESULTS_DIR / "e1_baselines.csv"),
        "default": load_and_validate(RESULTS_DIR / "e1_baselines_default.csv"),
    }
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    long_df = long_summary(frames)
    long_df.to_csv(OUTPUT_DIR / "e1_summary_long.csv", index=False)

    for metric in metrics:
        for variant, df in frames.items():
            wide = wide_table(df, metric)
            wide.to_csv(OUTPUT_DIR / f"e1_master_{variant}_{metric}.csv")
            caption = (f"E1 classical baselines ({variant}), {metric.replace('_', ' ')} "
                       f"mean $\\pm$ std over the 25 shared (seed, fold) evaluations.")
            (OUTPUT_DIR / f"e1_master_{variant}_{metric}.tex").write_text(
                to_latex(wide, caption, f"tab:e1-{variant}-{metric}"))
        delta = delta_table(frames["tuned"], frames["default"], metric)
        delta.to_csv(OUTPUT_DIR / f"e1_delta_{metric}.csv")
        (OUTPUT_DIR / f"e1_delta_{metric}.tex").write_text(
            to_latex(delta, f"Tuning gain: tuned minus default mean {metric.replace('_', ' ')}.",
                     f"tab:e1-delta-{metric}"))

    headline = args.metric if args.metric != "all" else "balanced_accuracy"
    print(f"== E1 master table (tuned, {headline}) ==")
    print(wide_table(frames["tuned"], headline).to_string())
    print(f"\n== tuning gain (tuned − default, mean {headline}) ==")
    print(delta_table(frames["tuned"], frames["default"], headline).to_string())
    print(f"\nwrote tables -> {OUTPUT_DIR}")


if __name__ == "__main__":
    main()
